using UnityEngine;
using System.Collections.Generic;
using UnityEngine.SceneManagement;

// インスペクターに表示するための、名前とマテリアルのペアを保持するクラス
[System.Serializable]
public class MaterialEntry
{
    public string name;
    public Material material;
}

[System.Serializable]
public class MeshEntry
{
    public string name;
    public Mesh mesh;
}

// インスペクターに表示するための、名前とテクスチャのペアを保持するクラス
[System.Serializable]
public class TextureEntry
{
    public string name;
    public Texture2D texture;
}

// インスペクターに表示するための、名前とシェーダーのペアを保持するクラス
[System.Serializable]
public class ShaderEntry
{
    public string name;
    public Shader shader;
}

/// <summary>
/// ゲーム全体の設定を管理し、各機能（ParticleGeneratorなど）に指示を出す司令塔クラス。
/// </summary>
public class SystemManager : MonoBehaviour
{
    public List<GameObject> GeneratedObjects;

    [Header("参照するコンポーネント")]
    [Tooltip("パーティクルの生成を担当するGenerator")]
    public ParticleGenerator particleGenerator;

    [Header("オブジェクトのマテリアル")]
    [Tooltip("CreateObjectFromMpsでオブジェにつけるマテリアル")]
    public Material defaultMaterial;

    [Header("マテリアルリスト")]
    [Tooltip("名前とマテリアルを紐付けて登録します")]
    public List<MaterialEntry> materialList;

    [Header("メッシュリスト")]
    [Tooltip("名前とメッシュを紐付けて登録します")]
    public List<MeshEntry> meshList;

    [Header("テクスチャリスト")]
    [Tooltip("名前とテクスチャを紐付けて登録します（Shapeモジュール用など）")]
    public List<TextureEntry> textureList;

    [Header("シェーダーリスト")]
    [Tooltip("名前とシェーダーを紐付けて登録します（動的マテリアル生成用）")]
    public List<ShaderEntry> shaderList;

    // --- Private Fields ---
    private Dictionary<string, Material> materialDictionary;
    private Dictionary<string, Mesh> meshDictionary;
    private Dictionary<string, Texture2D> textureDictionary;
    private Dictionary<string, Shader> shaderDictionary;

    // Manages generated objects by their unique ID
    private Dictionary<string, GameObject> managedObjectsById = new Dictionary<string, GameObject>();

    private bool isTimeActive = true;
    [SerializeField] private GameObject grid;
    private bool isGridRendering = true;

    //[SerializeField] private Camera targetCamera;
    [SerializeField] private Material[] skyMaterials;
    private int currentSkyIndex = 0;

    void Awake()
    {
        // マテリアル辞書の構築
        materialDictionary = new Dictionary<string, Material>();
        if (materialList != null)
        {
            foreach (var entry in materialList)
            {
                if (entry != null && !string.IsNullOrEmpty(entry.name) && entry.material != null)
                {
                    if (!materialDictionary.ContainsKey(entry.name))
                    {
                        materialDictionary.Add(entry.name, entry.material);
                    }
                }
            }
        }

        // メッシュ辞書の構築
        meshDictionary = new Dictionary<string, Mesh>();
        if (meshList != null)
        {
            foreach (var entry in meshList)
            {
                if (entry != null && !string.IsNullOrEmpty(entry.name) && entry.mesh != null)
                {
                    if (!meshDictionary.ContainsKey(entry.name))
                    {
                        meshDictionary.Add(entry.name, entry.mesh);
                    }
                }
            }
        }

        // テクスチャ辞書の構築
        textureDictionary = new Dictionary<string, Texture2D>();
        if (textureList != null)
        {
            foreach (var entry in textureList)
            {
                if (entry != null && !string.IsNullOrEmpty(entry.name) && entry.texture != null)
                {
                    if (!textureDictionary.ContainsKey(entry.name))
                    {
                        textureDictionary.Add(entry.name, entry.texture);
                    }
                }
            }
        }

        // シェーダー辞書の構築
        shaderDictionary = new Dictionary<string, Shader>();
        if (shaderList != null)
        {
            foreach (var entry in shaderList)
            {
                if (entry != null && !string.IsNullOrEmpty(entry.name) && entry.shader != null)
                {
                    if (!shaderDictionary.ContainsKey(entry.name))
                    {
                        shaderDictionary.Add(entry.name, entry.shader);
                    }
                }
            }
        }
    }

    /// <summary>
    /// Creates and plays a particle system based on the mps code received from p5.js.
    /// </summary>
    /// <param name="mpsCode">The string generated by p5.js</param>
    /// <param name="objectId">The unique ID generated by p5.js</param>
    public void CreateAndSpawnParticleFromMps(string mpsCode, string objectId)
    {
        if (string.IsNullOrEmpty(mpsCode))
        {
            Debug.LogWarning("Received empty mps code. Skipped particle generation.");
            return;
        }

        try
        {
            // Parse時にtextureDictionaryとshaderDictionaryも渡す
            ParticlePreset preset = MpsParser.Parse(mpsCode, materialDictionary, meshDictionary, textureDictionary, shaderDictionary);

            if (particleGenerator != null)
            {
                GameObject newParticleObject = particleGenerator.SpawnParticle(Vector3.zero, preset);

                if (!string.IsNullOrEmpty(objectId))
                {
                    // If an object with the same ID already exists, destroy the old one.
                    if (managedObjectsById.TryGetValue(objectId, out GameObject oldObject))
                    {
                        if (oldObject != null)
                        {
                            GeneratedObjects.Remove(oldObject);
                            Destroy(oldObject);
                        }
                        managedObjectsById.Remove(objectId);
                    }
                    managedObjectsById.Add(objectId, newParticleObject);
                }
            }
            else
            {
                Debug.LogError("ParticleGenerator is not set in SystemManager.", this);
            }
        }
        catch (System.Exception e)
        {
            // LogErrorからLogWarningに変更し、WebGLビルドでの実行停止を防ぐ
            Debug.LogWarning($"Error parsing MPS code: {e.Message}\n{e.StackTrace}");
        }
    }

    /// <summary>
    /// mpsコードに基づいてGameObjectを生成します。
    /// </summary>
    /// <param name="mpsCode">オブジェクトのタイプを指定するmpsコード（例: "<~type (Cube)>"）</param>
    /// <param name="objectId">オブジェクトの一意のID</param>
    public void CreateObjectFromMps(string mpsCode, string objectId)
    {
        if (string.IsNullOrEmpty(mpsCode))
        {
            Debug.LogWarning("Received empty mps code for object creation. Skipped.");
            return;
        }

        try
        {
            ObjectCreationData creationData = MpsParser.ParseObjectCreation(mpsCode);
            GameObject newObject = null;
            string lowerType = creationData.objectType.ToLower();

            // ★デバッグログ: 何を作ろうとしているか確認
            Debug.Log($"[SystemManager] CreateObjectFromMps called. Type: {lowerType}, ID: {objectId}");

            // objectTypeに基づいてGameObjectを生成
            switch (lowerType)
            {
                case "empty":
                    newObject = new GameObject("Empty Object");
                    break;
                case "cube":
                    newObject = GameObject.CreatePrimitive(PrimitiveType.Cube);
                    break;
                case "sphere":
                    newObject = GameObject.CreatePrimitive(PrimitiveType.Sphere);
                    break;
                case "capsule":
                    newObject = GameObject.CreatePrimitive(PrimitiveType.Capsule);
                    break;
                case "cylinder":
                    newObject = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
                    break;
                case "plane":
                    newObject = GameObject.CreatePrimitive(PrimitiveType.Plane);
                    break;
                case "quad":
                    newObject = GameObject.CreatePrimitive(PrimitiveType.Quad);
                    break;
                default:
                    Debug.LogWarning($"Unknown object type: '{creationData.objectType}'. Creating an empty object instead.");
                    newObject = new GameObject(creationData.objectType);
                    break;
            }

            // 生成したオブジェクトをリストと辞書に追加
            if (newObject != null)
            {
                // MeshFilterが存在するか（アセットストリッピング対策の確認）
                if (lowerType != "empty" && newObject.GetComponent<MeshFilter>() == null)
                {
                    Debug.LogError($"[SystemManager] WARNING: {lowerType} created but MeshFilter is MISSING. It may be invisible due to WebGL Asset Stripping.");
                }

                // --- マテリアルとプロパティの適用 ---
                var rend = newObject.GetComponent<Renderer>();
                if (rend != null)
                {
                    // ベースとなるマテリアルの決定
                    Material baseMat = null;
                    if (defaultMaterial != null)
                    {
                        baseMat = defaultMaterial;
                    }
                    else if (rend.sharedMaterial != null)
                    {
                        // defaultMaterialが設定されていない場合は、Primitiveが元々持っているマテリアル(Default-Material)をベースにする
                        baseMat = rend.sharedMaterial;
                    }
                    else
                    {
                        // 最終手段としてStandardシェーダーを作成
                        baseMat = new Material(Shader.Find("Standard"));
                    }

                    // インスタンスマテリアルの作成（個別にプロパティを変更するため）
                    Material instanceMat = new Material(baseMat);

                    // 1. Base Color
                    if (creationData.baseColor.HasValue)
                    {
                        if (instanceMat.HasProperty("_BaseColor")) // URP / HDRP
                            instanceMat.SetColor("_BaseColor", creationData.baseColor.Value);
                        else if (instanceMat.HasProperty("_Color")) // Built-in Standard
                            instanceMat.SetColor("_Color", creationData.baseColor.Value);
                    }

                    // 2. Metallic
                    if (creationData.metallic.HasValue)
                    {
                        if (instanceMat.HasProperty("_Metallic"))
                            instanceMat.SetFloat("_Metallic", creationData.metallic.Value);
                    }

                    // 3. Smoothness
                    if (creationData.smoothness.HasValue)
                    {
                        if (instanceMat.HasProperty("_Smoothness")) // URP
                            instanceMat.SetFloat("_Smoothness", creationData.smoothness.Value);
                        else if (instanceMat.HasProperty("_Glossiness")) // Built-in Standard (Smoothness is often stored in _Glossiness)
                            instanceMat.SetFloat("_Glossiness", creationData.smoothness.Value);
                    }

                    // 4. Emission
                    if (creationData.emissionColor.HasValue || creationData.emissionIntensity.HasValue)
                    {
                        instanceMat.EnableKeyword("_EMISSION");

                        Color finalEmission = Color.black;

                        // 現在のEmission色を取得（既存の設定を維持するため）
                        if (instanceMat.HasProperty("_EmissionColor"))
                            finalEmission = instanceMat.GetColor("_EmissionColor");

                        // 色の上書き
                        if (creationData.emissionColor.HasValue)
                        {
                            finalEmission = creationData.emissionColor.Value;
                        }

                        // 強度の適用（HDRカラーとして強度を乗算）
                        if (creationData.emissionIntensity.HasValue)
                        {
                            // 単純な色 * 強度のアプローチ (Standard Shader等ではこれで光る)
                            // 元の色が黒(0,0,0)だと光らないので、色が未指定かつ強度が指定された場合は白をベースにする等の調整が必要かもしれないが、
                            // ここではユーザーが色も指定することを期待するか、ベースマテリアルの色を使う。

                            // もし色が真っ黒で、かつ色が指定されていなかった場合、白にしておく親切設計
                            if (finalEmission == Color.black && !creationData.emissionColor.HasValue)
                            {
                                finalEmission = Color.white;
                            }

                            float intensity = creationData.emissionIntensity.Value;
                            // HDRカラーの計算: 線形空間での強度乗算
                            float factor = Mathf.Pow(2, intensity); // EV値として扱う場合
                            // 単純倍率として扱う場合: finalEmission *= intensity;
                            // ここでは単純倍率として扱います（扱いやすいので）
                            finalEmission *= intensity;
                        }

                        if (instanceMat.HasProperty("_EmissionColor"))
                        {
                            instanceMat.SetColor("_EmissionColor", finalEmission);
                            instanceMat.globalIlluminationFlags = MaterialGlobalIlluminationFlags.RealtimeEmissive;
                        }
                    }

                    rend.material = instanceMat;
                }

                GeneratedObjects.Add(newObject);

                if (!string.IsNullOrEmpty(objectId))
                {
                    // 同じIDのオブジェクトが既に存在する場合は、古いものを破棄
                    if (managedObjectsById.TryGetValue(objectId, out GameObject oldObject))
                    {
                        if (oldObject != null)
                        {
                            GeneratedObjects.Remove(oldObject);
                            Destroy(oldObject);
                        }
                        managedObjectsById.Remove(objectId);
                    }
                    managedObjectsById.Add(objectId, newObject);
                    newObject.name = $"{creationData.objectType}_{objectId}"; // オブジェクト名をわかりやすく設定
                }

                Debug.Log($"[SystemManager] Successfully registered object: {newObject.name}");
            }
            else
            {
                Debug.LogError("[SystemManager] Failed to create object variable (newObject is null).");
            }
        }
        catch (System.Exception e)
        {
            // LogErrorからLogWarningに変更し、WebGLビルドでの実行停止を防ぐ
            Debug.LogWarning($"Error parsing object creation code: {e.Message}\n{e.StackTrace}");
        }
    }

    /// <summary>
    /// 指定されたIDのオブジェクトを、別の指定されたIDのオブジェクトの子にします。
    /// </summary>
    /// <param name="childId">子にするオブジェクトのID</param>
    /// <param name="parentId">親にするオブジェクトのID</param>
    public void AttachToParent(string childId, string parentId)
    {
        if (string.IsNullOrEmpty(childId) || string.IsNullOrEmpty(parentId))
        {
            Debug.LogWarning("Child ID or Parent ID is null or empty. Cannot attach.");
            return;
        }

        if (!managedObjectsById.TryGetValue(childId, out GameObject childObject))
        {
            Debug.LogWarning($"Child object with ID '{childId}' not found.");
            return;
        }

        if (!managedObjectsById.TryGetValue(parentId, out GameObject parentObject))
        {
            Debug.LogWarning($"Parent object with ID '{parentId}' not found.");
            return;
        }

        if (childObject == null)
        {
            Debug.LogWarning($"Child object with ID '{childId}' has been destroyed.");
            managedObjectsById.Remove(childId);
            return;
        }

        if (parentObject == null)
        {
            Debug.LogWarning($"Parent object with ID '{parentId}' has been destroyed.");
            managedObjectsById.Remove(parentId);
            return;
        }

        // Set the parent
        childObject.transform.SetParent(parentObject.transform);
        Debug.Log($"Attached object '{childId}' to parent '{parentId}'.");
    }

    /// <summary>
    /// Updates the Transform of a GameObject specified by its ID.
    /// </summary>
    /// <param name="objectId">The ID of the target object</param>
    /// <param name="transformCode">The mps string containing position, rotation, and scale information</param>
    public void TransformObjectById(string objectId, string transformCode)
    {
        if (string.IsNullOrEmpty(objectId) || !managedObjectsById.ContainsKey(objectId))
        {
            Debug.LogWarning($"Transform target object with ID '{objectId}' not found.");
            return;
        }

        GameObject objToTransform = managedObjectsById[objectId];
        if (objToTransform == null)
        {
            Debug.LogWarning($"Target object with ID '{objectId}' has already been destroyed.");
            managedObjectsById.Remove(objectId);
            return;
        }

        try
        {
            TransformData transformData = MpsParser.ParseTransform(transformCode);

            if (transformData.position.HasValue)
            {
                objToTransform.transform.position = transformData.position.Value;
            }
            if (transformData.rotation.HasValue)
            {
                objToTransform.transform.localEulerAngles = transformData.rotation.Value;
            }
            if (transformData.scale.HasValue)
            {
                objToTransform.transform.localScale = transformData.scale.Value;
            }
        }
        catch (System.Exception e)
        {
            // LogErrorからLogWarningに変更し、WebGLビルドでの実行停止を防ぐ
            Debug.LogWarning($"Error parsing Transform code: {e.Message}\n{e.StackTrace}");
        }
    }

    public void AnimationObjectById(string objectId, string animationCode)
    {
        if (string.IsNullOrEmpty(objectId) || !managedObjectsById.ContainsKey(objectId))
        {
            Debug.LogWarning($"Animation target object with ID '{objectId}' not found.");
            return;
        }

        GameObject objToAnimation = managedObjectsById[objectId];
        if (objToAnimation == null)
        {
            Debug.LogWarning($"Target object with ID '{objectId}' has already been destroyed.");
            managedObjectsById.Remove(objectId);
            return;
        }

        try
        {
            AnimationDatas animationDatas = MpsParser.ParseAnimation(animationCode);
            TransformAnimation anim = null;
            if (objToAnimation.GetComponent<TransformAnimation>() == null)
                anim = objToAnimation.AddComponent<TransformAnimation>();
            else
                anim = objToAnimation.GetComponent<TransformAnimation>();
            anim.Initialize(animationDatas);
        }
        catch (System.Exception e)
        {
            // LogErrorからLogWarningに変更し、WebGLビルドでの実行停止を防ぐ
            Debug.LogWarning($"Error parsing Animation code: {e.Message}\n{e.StackTrace}");
        }
    }

    public void Reset()
    {
        isTimeActive = true;
        Time.timeScale = 1.0f;
        foreach (GameObject obj in GeneratedObjects)
        {
            Destroy(obj);
        }
        GeneratedObjects.Clear();
        managedObjectsById.Clear();
    }

    public void SwitchTimeScale()
    {
        isTimeActive = !isTimeActive;
        Time.timeScale = isTimeActive ? 1.0f : 0.0f;
    }

    public void ReloadScene()
    {
        SceneManager.LoadScene(SceneManager.GetActiveScene().name);
    }

    public void SwitchGridView()
    {
        isGridRendering = !isGridRendering;
        grid.GetComponent<MeshRenderer>().enabled = isGridRendering;
    }

    public void SwitchSkyBox()
    {
        currentSkyIndex = (currentSkyIndex + 1) % skyMaterials.Length;
        RenderSettings.skybox = skyMaterials[currentSkyIndex];
    }
}