using UnityEngine;
using System.Collections.Generic;

// インスペクターに表示するための、名前とマテリアルのペアを保持するクラス
[System.Serializable]
public class MaterialEntry
{
    public string name;
    public Material material;
}

[System.Serializable]
public class MeshEntry
{
    public string name;
    public Mesh mesh;
}

/// <summary>
/// ゲーム全体の設定を管理し、各機能（ParticleGeneratorなど）に指示を出す司令塔クラス。
/// </summary>
public class SystemManager : MonoBehaviour
{
    public List<GameObject> GeneratedObjects;

    [Header("参照するコンポーネント")]
    [Tooltip("パーティクルの生成を担当するGenerator")]
    public ParticleGenerator particleGenerator;

    [Header("マテリアルリスト")]
    [Tooltip("名前とマテリアルを紐付けて登録します")]
    public List<MaterialEntry> materialList;

    [Header("メッシュリスト")]
    [Tooltip("名前とメッシュを紐付けて登録します")]
    public List<MeshEntry> meshList;

    // --- Private Fields ---
    private Dictionary<string, Material> materialDictionary;
    private Dictionary<string, Mesh> meshDictionary;
    // Manages generated objects by their unique ID
    private Dictionary<string, GameObject> managedObjectsById = new Dictionary<string, GameObject>();

    void Awake()
    {
        materialDictionary = new Dictionary<string, Material>();
        foreach (var entry in materialList)
        {
            if (entry != null && !string.IsNullOrEmpty(entry.name) && entry.material != null)
            {
                if (!materialDictionary.ContainsKey(entry.name))
                {
                    materialDictionary.Add(entry.name, entry.material);
                }
            }
        }
        meshDictionary = new Dictionary<string, Mesh>();
        foreach (var entry in meshList)
        {
            if (entry != null && !string.IsNullOrEmpty(entry.name) && entry.mesh != null)
            {
                if (!meshDictionary.ContainsKey(entry.name))
                {
                    meshDictionary.Add(entry.name, entry.mesh);
                }
            }
        }
    }

    /// <summary>
    /// Creates and plays a particle system based on the mps code received from p5.js.
    /// </summary>
    /// <param name="mpsCode">The string generated by p5.js</param>
    /// <param name="objectId">The unique ID generated by p5.js</param>
    public void CreateAndSpawnParticleFromMps(string mpsCode, string objectId)
    {
        if (string.IsNullOrEmpty(mpsCode))
        {
            Debug.LogWarning("Received empty mps code. Skipped particle generation.");
            return;
        }

        try
        {
            ParticlePreset preset = MpsParser.Parse(mpsCode, materialDictionary, meshDictionary);

            if (particleGenerator != null)
            {
                GameObject newParticleObject = particleGenerator.SpawnParticle(Vector3.zero, preset);

                if (!string.IsNullOrEmpty(objectId))
                {
                    // If an object with the same ID already exists, destroy the old one.
                    if (managedObjectsById.TryGetValue(objectId, out GameObject oldObject))
                    {
                        if (oldObject != null)
                        {
                            GeneratedObjects.Remove(oldObject);
                            Destroy(oldObject);
                        }
                        managedObjectsById.Remove(objectId);
                    }
                    managedObjectsById.Add(objectId, newParticleObject);
                }
            }
            else
            {
                Debug.LogError("ParticleGenerator is not set in SystemManager.", this);
            }
        }
        catch (System.Exception e)
        {
            Debug.LogError($"Error parsing MPS code: {e.Message}\n{e.StackTrace}");
        }
    }

    /// <summary>
    /// mpsコードに基づいてGameObjectを生成します。
    /// </summary>
    /// <param name="mpsCode">オブジェクトのタイプを指定するmpsコード（例: "<~type (Cube)>"）</param>
    /// <param name="objectId">オブジェクトの一意のID</param>
    public void CreateObjectFromMps(string mpsCode, string objectId)
    {
        if (string.IsNullOrEmpty(mpsCode))
        {
            Debug.LogWarning("Received empty mps code for object creation. Skipped.");
            return;
        }

        try
        {
            ObjectCreationData creationData = MpsParser.ParseObjectCreation(mpsCode);
            GameObject newObject = null;

            // objectTypeに基づいてGameObjectを生成
            switch (creationData.objectType.ToLower()) // 小文字に変換して比較
            {
                case "empty":
                    newObject = new GameObject("Empty Object");
                    break;
                case "cube":
                    newObject = GameObject.CreatePrimitive(PrimitiveType.Cube);
                    break;
                case "sphere":
                    newObject = GameObject.CreatePrimitive(PrimitiveType.Sphere);
                    break;
                case "capsule":
                    newObject = GameObject.CreatePrimitive(PrimitiveType.Capsule);
                    break;
                case "cylinder":
                    newObject = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
                    break;
                case "plane":
                    newObject = GameObject.CreatePrimitive(PrimitiveType.Plane);
                    break;
                case "quad":
                    newObject = GameObject.CreatePrimitive(PrimitiveType.Quad);
                    break;
                default:
                    Debug.LogWarning($"Unknown object type: '{creationData.objectType}'. Creating an empty object instead.");
                    newObject = new GameObject(creationData.objectType);
                    break;
            }

            // 生成したオブジェクトをリストと辞書に追加
            if (newObject != null)
            {
                GeneratedObjects.Add(newObject);

                if (!string.IsNullOrEmpty(objectId))
                {
                    // 同じIDのオブジェクトが既に存在する場合は、古いものを破棄
                    if (managedObjectsById.TryGetValue(objectId, out GameObject oldObject))
                    {
                        if (oldObject != null)
                        {
                            GeneratedObjects.Remove(oldObject);
                            Destroy(oldObject);
                        }
                        managedObjectsById.Remove(objectId);
                    }
                    managedObjectsById.Add(objectId, newObject);
                    newObject.name = $"{creationData.objectType}_{objectId}"; // オブジェクト名をわかりやすく設定
                }
            }
        }
        catch (System.Exception e)
        {
            Debug.LogError($"Error parsing object creation code: {e.Message}\n{e.StackTrace}");
        }
    }

    /// <summary>
    /// 指定されたIDのオブジェクトを、別の指定されたIDのオブジェクトの子にします。
    /// </summary>
    /// <param name="childId">子にするオブジェクトのID</param>
    /// <param name="parentId">親にするオブジェクトのID</param>
    public void AttachToParent(string childId, string parentId)
    {
        if (string.IsNullOrEmpty(childId) || string.IsNullOrEmpty(parentId))
        {
            Debug.LogWarning("Child ID or Parent ID is null or empty. Cannot attach.");
            return;
        }

        if (!managedObjectsById.TryGetValue(childId, out GameObject childObject))
        {
            Debug.LogWarning($"Child object with ID '{childId}' not found.");
            return;
        }

        if (!managedObjectsById.TryGetValue(parentId, out GameObject parentObject))
        {
            Debug.LogWarning($"Parent object with ID '{parentId}' not found.");
            return;
        }

        if (childObject == null)
        {
            Debug.LogWarning($"Child object with ID '{childId}' has been destroyed.");
            managedObjectsById.Remove(childId);
            return;
        }

        if (parentObject == null)
        {
            Debug.LogWarning($"Parent object with ID '{parentId}' has been destroyed.");
            managedObjectsById.Remove(parentId);
            return;
        }

        // Set the parent
        childObject.transform.SetParent(parentObject.transform);
        Debug.Log($"Attached object '{childId}' to parent '{parentId}'.");
    }

    /// <summary>
    /// Updates the Transform of a GameObject specified by its ID.
    /// </summary>
    /// <param name="objectId">The ID of the target object</param>
    /// <param name="transformCode">The mps string containing position, rotation, and scale information</param>
    public void TransformObjectById(string objectId, string transformCode)
    {
        if (string.IsNullOrEmpty(objectId) || !managedObjectsById.ContainsKey(objectId))
        {
            Debug.LogWarning($"Transform target object with ID '{objectId}' not found.");
            return;
        }

        GameObject objToTransform = managedObjectsById[objectId];
        if (objToTransform == null)
        {
            Debug.LogWarning($"Target object with ID '{objectId}' has already been destroyed.");
            managedObjectsById.Remove(objectId);
            return;
        }

        try
        {
            TransformData transformData = MpsParser.ParseTransform(transformCode);

            if (transformData.position.HasValue)
            {
                objToTransform.transform.position = transformData.position.Value;
            }
            if (transformData.rotation.HasValue)
            {
                objToTransform.transform.localEulerAngles = transformData.rotation.Value;
            }
            if (transformData.scale.HasValue)
            {
                objToTransform.transform.localScale = transformData.scale.Value;
            }
        }
        catch (System.Exception e)
        {
            Debug.LogError($"Error parsing Transform code: {e.Message}\n{e.StackTrace}");
        }
    }

    public void AnimationObjectById(string objectId, string animationCode)
    {
        if (string.IsNullOrEmpty(objectId) || !managedObjectsById.ContainsKey(objectId))
        {
            Debug.LogWarning($"Animation target object with ID '{objectId}' not found.");
            return;
        }

        GameObject objToAnimation = managedObjectsById[objectId];
        if (objToAnimation == null)
        {
            Debug.LogWarning($"Target object with ID '{objectId}' has already been destroyed.");
            managedObjectsById.Remove(objectId);
            return;
        }

        try
        {
            AnimationDatas animationDatas = MpsParser.ParseAnimation(animationCode);
            TransformAnimation anim = null;
            if (objToAnimation.GetComponent<TransformAnimation>() == null)
                anim = objToAnimation.AddComponent<TransformAnimation>();
            else
                anim = objToAnimation.GetComponent<TransformAnimation>();
            anim.Initialize(animationDatas);
        }
        catch (System.Exception e)
        {
            Debug.LogError($"Error parsing Animation code: {e.Message}\n{e.StackTrace}");
        }
    }

    public void Reset()
    {
        foreach (GameObject obj in GeneratedObjects)
        {
            Destroy(obj);
        }
        GeneratedObjects.Clear();
        managedObjectsById.Clear();
    }
}
