using UnityEngine;
using System.Collections.Generic;

// インスペクターに表示するための、名前とマテリアルのペアを保持するクラス
[System.Serializable]
public class MaterialEntry
{
    public string name;
    public Material material;
}

/// <summary>
/// ゲーム全体の設定を管理し、各機能（ParticleGeneratorなど）に指示を出す司令塔クラス。
/// </summary>
public class SystemManager : MonoBehaviour
{
    public List<GameObject> GeneratedObjects;

    [Header("参照するコンポーネント")]
    [Tooltip("パーティクルの生成を担当するGenerator")]
    public ParticleGenerator particleGenerator;

    [Header("マテリアルリスト")]
    [Tooltip("名前とマテリアルを紐付けて登録します")]
    public List<MaterialEntry> materialList;

    // --- Private Fields ---
    private Dictionary<string, Material> materialDictionary;
    // Manages generated objects by their unique ID
    private Dictionary<string, GameObject> managedObjectsById = new Dictionary<string, GameObject>();

    void Awake()
    {
        materialDictionary = new Dictionary<string, Material>();
        foreach (var entry in materialList)
        {
            if (entry != null && !string.IsNullOrEmpty(entry.name) && entry.material != null)
            {
                if (!materialDictionary.ContainsKey(entry.name))
                {
                    materialDictionary.Add(entry.name, entry.material);
                }
            }
        }
    }

    /// <summary>
    /// Creates and plays a particle system based on the mps code received from p5.js.
    /// </summary>
    /// <param name="mpsCode">The string generated by p5.js</param>
    /// <param name="objectId">The unique ID generated by p5.js</param>
    public void CreateAndSpawnParticleFromMps(string mpsCode, string objectId)
    {
        if (string.IsNullOrEmpty(mpsCode))
        {
            Debug.LogWarning("Received empty mps code. Skipped particle generation.");
            return;
        }

        try
        {
            ParticlePreset preset = MpsParser.Parse(mpsCode, materialDictionary);

            if (particleGenerator != null)
            {
                GameObject newParticleObject = particleGenerator.SpawnParticle(Vector3.zero, preset);

                if (!string.IsNullOrEmpty(objectId))
                {
                    // If an object with the same ID already exists, destroy the old one.
                    if (managedObjectsById.TryGetValue(objectId, out GameObject oldObject))
                    {
                        if (oldObject != null) Destroy(oldObject);
                        managedObjectsById.Remove(objectId);
                    }
                    managedObjectsById.Add(objectId, newParticleObject);
                }
            }
            else
            {
                Debug.LogError("ParticleGenerator is not set in SystemManager.", this);
            }
        }
        catch (System.Exception e)
        {
            Debug.LogError($"Error parsing MPS code: {e.Message}\n{e.StackTrace}");
        }
    }

    /// <summary>
    /// Updates the Transform of a GameObject specified by its ID.
    /// </summary>
    /// <param name="objectId">The ID of the target object</param>
    /// <param name="transformCode">The mps string containing position, rotation, and scale information</param>
    public void TransformObjectById(string objectId, string transformCode)
    {
        if (string.IsNullOrEmpty(objectId) || !managedObjectsById.ContainsKey(objectId))
        {
            Debug.LogWarning($"Transform target object with ID '{objectId}' not found.");
            return;
        }

        GameObject objToTransform = managedObjectsById[objectId];
        if (objToTransform == null)
        {
            Debug.LogWarning($"Target object with ID '{objectId}' has already been destroyed.");
            managedObjectsById.Remove(objectId);
            return;
        }

        try
        {
            TransformData transformData = MpsParser.ParseTransform(transformCode);

            if (transformData.position.HasValue)
            {
                objToTransform.transform.position = transformData.position.Value;
            }
            if (transformData.rotation.HasValue)
            {
                objToTransform.transform.eulerAngles = transformData.rotation.Value;
            }
            if (transformData.scale.HasValue)
            {
                objToTransform.transform.localScale = transformData.scale.Value;
            }
        }
        catch (System.Exception e)
        {
            Debug.LogError($"Error parsing Transform code: {e.Message}\n{e.StackTrace}");
        }
    }

    public void AnimationObjectById(string objectId, string animationCode)
    {
        if (string.IsNullOrEmpty(objectId) || !managedObjectsById.ContainsKey(objectId))
        {
            Debug.LogWarning($"Animation target object with ID '{objectId}' not found.");
            return;
        }

        GameObject objToAnimation = managedObjectsById[objectId];
        if (objToAnimation == null)
        {
            Debug.LogWarning($"Target object with ID '{objectId}' has already been destroyed.");
            managedObjectsById.Remove(objectId);
            return;
        }

        try
        {
            AnimationDatas animationDatas = MpsParser.ParseAnimation(animationCode);
            TransformAnimation anim = null;
            if (objToAnimation.GetComponent<TransformAnimation>() == null)
                anim = objToAnimation.AddComponent<TransformAnimation>();
            else
                anim = objToAnimation.GetComponent<TransformAnimation>();
            anim.Initialize(animationDatas);
        }
        catch (System.Exception e)
        {
            Debug.LogError($"Error parsing Animation code: {e.Message}\n{e.StackTrace}");
        }
    }

    public void Reset()
    {
        foreach (GameObject obj in GeneratedObjects)
        {
            Destroy(obj);
        }
        GeneratedObjects.Clear();
        managedObjectsById.Clear();
    }
}
